# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import nlp_pb2 as nlp__pb2


class NlpStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Tokenize = channel.unary_unary(
                '/thread.Nlp/Tokenize',
                request_serializer=nlp__pb2.TokenizeParagraph.SerializeToString,
                response_deserializer=nlp__pb2.TokenizeSentences.FromString,
                )
        self.Embed = channel.unary_unary(
                '/thread.Nlp/Embed',
                request_serializer=nlp__pb2.EmbedSentence.SerializeToString,
                response_deserializer=nlp__pb2.EncodedSentence.FromString,
                )
        self.Measure = channel.unary_unary(
                '/thread.Nlp/Measure',
                request_serializer=nlp__pb2.MeasureVectors.SerializeToString,
                response_deserializer=nlp__pb2.MeasureSimilarity.FromString,
                )


class NlpServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Tokenize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Embed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Measure(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NlpServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Tokenize': grpc.unary_unary_rpc_method_handler(
                    servicer.Tokenize,
                    request_deserializer=nlp__pb2.TokenizeParagraph.FromString,
                    response_serializer=nlp__pb2.TokenizeSentences.SerializeToString,
            ),
            'Embed': grpc.unary_unary_rpc_method_handler(
                    servicer.Embed,
                    request_deserializer=nlp__pb2.EmbedSentence.FromString,
                    response_serializer=nlp__pb2.EncodedSentence.SerializeToString,
            ),
            'Measure': grpc.unary_unary_rpc_method_handler(
                    servicer.Measure,
                    request_deserializer=nlp__pb2.MeasureVectors.FromString,
                    response_serializer=nlp__pb2.MeasureSimilarity.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'thread.Nlp', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Nlp(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Tokenize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/thread.Nlp/Tokenize',
            nlp__pb2.TokenizeParagraph.SerializeToString,
            nlp__pb2.TokenizeSentences.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Embed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/thread.Nlp/Embed',
            nlp__pb2.EmbedSentence.SerializeToString,
            nlp__pb2.EncodedSentence.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Measure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/thread.Nlp/Measure',
            nlp__pb2.MeasureVectors.SerializeToString,
            nlp__pb2.MeasureSimilarity.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
