[workspace]
members = [
  "service",
  "service-core",
  "service-macros"
]

[profile.release]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
rpath = false
lto = true
panic = "abort"
codegen-units = 8
incremental = false