// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.2
// source: exam.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ExamClient is the client API for Exam service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExamClient interface {
	CreateExam(ctx context.Context, in *ExamCreateBody, opts ...grpc.CallOption) (*ExamBody, error)
	GetExams(ctx context.Context, in *ExamPropertyRequestBody, opts ...grpc.CallOption) (*ExamBodyArr, error)
	UpdateExamByCourseProperty(ctx context.Context, in *ExamRequestUpdateBody, opts ...grpc.CallOption) (*ExamBody, error)
	DeleteExamByCourseProperty(ctx context.Context, in *ExamPropertyRequestBody, opts ...grpc.CallOption) (*ExamBody, error)
}

type examClient struct {
	cc grpc.ClientConnInterface
}

func NewExamClient(cc grpc.ClientConnInterface) ExamClient {
	return &examClient{cc}
}

func (c *examClient) CreateExam(ctx context.Context, in *ExamCreateBody, opts ...grpc.CallOption) (*ExamBody, error) {
	out := new(ExamBody)
	err := c.cc.Invoke(ctx, "/exam.Exam/CreateExam", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examClient) GetExams(ctx context.Context, in *ExamPropertyRequestBody, opts ...grpc.CallOption) (*ExamBodyArr, error) {
	out := new(ExamBodyArr)
	err := c.cc.Invoke(ctx, "/exam.Exam/GetExams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examClient) UpdateExamByCourseProperty(ctx context.Context, in *ExamRequestUpdateBody, opts ...grpc.CallOption) (*ExamBody, error) {
	out := new(ExamBody)
	err := c.cc.Invoke(ctx, "/exam.Exam/UpdateExamByCourseProperty", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *examClient) DeleteExamByCourseProperty(ctx context.Context, in *ExamPropertyRequestBody, opts ...grpc.CallOption) (*ExamBody, error) {
	out := new(ExamBody)
	err := c.cc.Invoke(ctx, "/exam.Exam/DeleteExamByCourseProperty", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExamServer is the server API for Exam service.
// All implementations should embed UnimplementedExamServer
// for forward compatibility
type ExamServer interface {
	CreateExam(context.Context, *ExamCreateBody) (*ExamBody, error)
	GetExams(context.Context, *ExamPropertyRequestBody) (*ExamBodyArr, error)
	UpdateExamByCourseProperty(context.Context, *ExamRequestUpdateBody) (*ExamBody, error)
	DeleteExamByCourseProperty(context.Context, *ExamPropertyRequestBody) (*ExamBody, error)
}

// UnimplementedExamServer should be embedded to have forward compatible implementations.
type UnimplementedExamServer struct {
}

func (UnimplementedExamServer) CreateExam(context.Context, *ExamCreateBody) (*ExamBody, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateExam not implemented")
}
func (UnimplementedExamServer) GetExams(context.Context, *ExamPropertyRequestBody) (*ExamBodyArr, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExams not implemented")
}
func (UnimplementedExamServer) UpdateExamByCourseProperty(context.Context, *ExamRequestUpdateBody) (*ExamBody, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateExamByCourseProperty not implemented")
}
func (UnimplementedExamServer) DeleteExamByCourseProperty(context.Context, *ExamPropertyRequestBody) (*ExamBody, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteExamByCourseProperty not implemented")
}

// UnsafeExamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExamServer will
// result in compilation errors.
type UnsafeExamServer interface {
	mustEmbedUnimplementedExamServer()
}

func RegisterExamServer(s grpc.ServiceRegistrar, srv ExamServer) {
	s.RegisterService(&Exam_ServiceDesc, srv)
}

func _Exam_CreateExam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExamCreateBody)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServer).CreateExam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/exam.Exam/CreateExam",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServer).CreateExam(ctx, req.(*ExamCreateBody))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exam_GetExams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExamPropertyRequestBody)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServer).GetExams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/exam.Exam/GetExams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServer).GetExams(ctx, req.(*ExamPropertyRequestBody))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exam_UpdateExamByCourseProperty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExamRequestUpdateBody)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServer).UpdateExamByCourseProperty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/exam.Exam/UpdateExamByCourseProperty",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServer).UpdateExamByCourseProperty(ctx, req.(*ExamRequestUpdateBody))
	}
	return interceptor(ctx, in, info, handler)
}

func _Exam_DeleteExamByCourseProperty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExamPropertyRequestBody)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamServer).DeleteExamByCourseProperty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/exam.Exam/DeleteExamByCourseProperty",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamServer).DeleteExamByCourseProperty(ctx, req.(*ExamPropertyRequestBody))
	}
	return interceptor(ctx, in, info, handler)
}

// Exam_ServiceDesc is the grpc.ServiceDesc for Exam service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Exam_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "exam.Exam",
	HandlerType: (*ExamServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateExam",
			Handler:    _Exam_CreateExam_Handler,
		},
		{
			MethodName: "GetExams",
			Handler:    _Exam_GetExams_Handler,
		},
		{
			MethodName: "UpdateExamByCourseProperty",
			Handler:    _Exam_UpdateExamByCourseProperty_Handler,
		},
		{
			MethodName: "DeleteExamByCourseProperty",
			Handler:    _Exam_DeleteExamByCourseProperty_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "exam.proto",
}
