[package]
name = "service-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mongodb = "2.3.1"
serde_yaml = "0.9.14"
thiserror = "1.0.37"
tonic = "0.8.2"
