name: Auth service build test

on:
  push:
    paths:
      - 'apps/auth/**'
      - 'apps/proto/auth.proto'
      - 'apps/proto/user.proto'

jobs:
  build:
    name: Building auth service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update rust
        run: rustup update

      - name: Install Protoc
        uses: arduino/setup-protoc@v1

      - run: cargo build
        working-directory: apps/auth
